# Generated by Django 4.1.7 on 2023-02-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ranking_system',
            field=models.IntegerField(null=True),
        ),
    ]
