# Generated by Django 4.1.7 on 2023-02-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_ranking_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='members_city',
            field=models.CharField(default='SOME STRING', max_length=80),
        ),
        migrations.AddField(
            model_name='member',
            name='total_scores',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='user_email',
            field=models.CharField(default='SOME STRING', max_length=80),
        ),
    ]
